name: Build & Push Image
on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - entrypoint.sh
      - .github/workflows/build.yml
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: onichandame
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile
          tags: onichandame/desktop
          cache-from: type=registry,ref=onichandame/desktop:latest
          cache-to: type=inline
  sync:
    name: Sync Image to Aliyun Container Registry
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: onichandame/docker-registry-sync-action@1.1.0
        with:
          source_repository: docker.io/onichandame/desktop
          source_username: onichandame
          source_password: ${{ secrets.DOCKER_PASSWORD }}
          target_repository: registry.cn-shanghai.aliyuncs.com/onichandame/desktop
          target_username: ${{ secrets.ALIYUN_IMAGES_HUB_USERNAME }}
          target_password: ${{ secrets.ALIYUN_IMAGES_HUB_PASSWORD }}
